"""empty message

Revision ID: 078388c2374b
Revises: 873f03f5774a
Create Date: 2020-10-13 18:48:40.489475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078388c2374b'
down_revision = '873f03f5774a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
