"""empty message

Revision ID: 9451fe3e5b87
Revises: ac848f0aca64
Create Date: 2020-10-10 13:28:22.231269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9451fe3e5b87'
down_revision = 'ac848f0aca64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE Venue SET num_upcoming_shows=0 Where num_upcoming_shows IS NULL;')
    op.alter_column('Venue','num_upcoming_shows',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'num_upcoming_shows')
    # ### end Alembic commands ###
