"""empty message

Revision ID: a42d57950a9f
Revises: 9451fe3e5b87
Create Date: 2020-10-10 17:30:19.374910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42d57950a9f'
down_revision = '9451fe3e5b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('num_upcoming_shows', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE Artist SET num_upcoming_shows=0 Where num_upcoming_shows IS NULL;')
    op.alter_column('Artist','num_upcoming_shows',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'num_upcoming_shows')
    # ### end Alembic commands ###
